from functools import lru_cache

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Application settings loaded from environment variables and optional .env file.

    Precedence (highest first): environment variables → .env file → defaults.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # OpenSearch
    opensearch_host: str = "localhost"
    opensearch_port: int = 9200
    opensearch_use_ssl: bool = False
    opensearch_verify_certs: bool = False
    opensearch_index_name: str = "travel_hotels"

    # Application
    log_level: str = "INFO"
    # log_format: "text" (default, human-readable) or "json" (NDJSON for production).
    # When "json", all travel_ai_search.* log records are serialised as one JSON
    # object per line, making them directly queryable by Loki, CloudWatch, etc.
    log_format: str = "text"
    environment: str = "development"

    # Search
    top_k: int = 10

    # Embeddings
    # Change embedding_model_name to switch models, but also update
    # embedding_dimension to match and recreate the index (dimension is immutable).
    embedding_model_name: str = "all-MiniLM-L6-v2"
    embedding_dimension: int = 384

    # Hybrid retrieval (Milestone 6)
    # lexical_weight + vector_weight need not sum to 1.0; they are applied to
    # independently min-max-normalised scores, so the ratio is what matters.
    hybrid_lexical_weight: float = 0.5
    hybrid_vector_weight: float = 0.5
    hybrid_candidate_k: int = 50

    # Fusion strategy (Milestone 7)
    # hybrid_fusion: default fusion method — "weighted" or "rrf"
    # rrf_k: smoothing constant in RRF formula 1/(k + rank); k=60 is the
    #   empirically robust default from Cormack et al. (2009)
    hybrid_fusion: str = "weighted"
    rrf_k: int = 60

    # Reranking (Milestone 8)
    # reranking_enabled: set True to load the cross-encoder at startup.
    #   When False, the reranker is never loaded and reranking is a no-op
    #   even if rerank=true is passed to the API endpoint.
    # reranker_model_name: any cross-encoder model from HuggingFace Hub.
    #   Smaller/faster: cross-encoder/ms-marco-MiniLM-L-2-v2
    #   Larger/better:  cross-encoder/ms-marco-MiniLM-L-12-v2
    # rerank_k: candidates passed to the cross-encoder (must be ≥ top_k).
    reranking_enabled: bool = False
    reranker_model_name: str = "cross-encoder/ms-marco-MiniLM-L-6-v2"
    rerank_k: int = 50

    # Query understanding (Milestone 9)
    # query_understanding_enabled: controls whether the QU engine is created at startup.
    #   The rule-based engine is pure Python and costs nothing to load; this flag
    #   exists to allow disabling it (e.g. for A/B testing) without code changes.
    query_understanding_enabled: bool = True

    # Query rewriting (Milestone 10)
    # query_rewriting_enabled: set True to create a QueryRewriter at startup.
    #   When False, the rewriter is never created and rewrite=true in POST /search
    #   is silently ignored (retrieval uses the semantic_query as-is).
    # llm_provider: which local provider to use — "local" (keyword expansion) or
    #   "echo" (identity stub, for testing).  "bedrock" is added in Milestone 12.
    query_rewriting_enabled: bool = False
    llm_provider: str = "local"

    # Query expansion / multi-query retrieval (Milestone 11)
    # query_expansion_enabled: set True to create a QueryExpander at startup.
    #   When False, the expander is never created and expand=true in POST /search
    #   is silently ignored (falls back to single-query hybrid retrieval).
    # num_expansion_queries: number of query variants to generate per request.
    #   The first variant is always the original query; additional variants are
    #   generated by LocalQueryExpander (synonym substitution + context elaboration).
    query_expansion_enabled: bool = False
    num_expansion_queries: int = 3

    # AWS Bedrock (Milestone 12)
    # AWS is optional — the full system runs locally without these settings.
    # aws_region: Bedrock API region.  us-east-1 has the widest model availability.
    #
    # embedding_provider: "local" (sentence-transformers) or "bedrock" (Titan Embeddings).
    #   Switching local→bedrock changes the vector dimension (384→1024 by default),
    #   which requires recreating the OpenSearch index.  Set both embedding_dimension
    #   and bedrock_embedding_dimension to 1024, then run:
    #     make create-index && make generate-embeddings
    # bedrock_embedding_model_id: Amazon Titan Embeddings V2 model ID.
    # bedrock_embedding_dimension: output dimension (256, 512, or 1024).
    #
    # llm_provider: "local", "echo", or "bedrock" (Claude via Converse API).
    # bedrock_llm_model_id: any Converse-compatible model ID on Bedrock.
    #
    # reranker_provider: "local" (ms-marco cross-encoder) or "bedrock" (Cohere Rerank).
    # bedrock_reranker_model_id: Cohere Rerank model ID.
    aws_region: str = "us-east-1"
    embedding_provider: str = "local"
    bedrock_embedding_model_id: str = "amazon.titan-embed-text-v2:0"
    bedrock_embedding_dimension: int = 1024
    bedrock_llm_model_id: str = "anthropic.claude-haiku-4-5-20251001"
    reranker_provider: str = "local"
    bedrock_reranker_model_id: str = "cohere.rerank-v3-5:0"

    # RAG / destination knowledge base (Milestone 13)
    # rag_enabled: set True to create KnowledgeRetriever and RAGSynthesizer at startup.
    #   When False, rag=true in POST /search is silently ignored.
    # knowledge_index_name: OpenSearch index for destination documents.
    #   Run `make ingest-knowledge` after changing this.
    # rag_context_k: number of destination knowledge documents to retrieve per query.
    rag_enabled: bool = False
    knowledge_index_name: str = "travel_destinations"
    rag_context_k: int = 3

    # Graph-enhanced retrieval (Milestone 14)
    # graph_enabled: set False to skip building the destination graph at startup.
    #   When False, all /graph/* endpoints return HTTP 503.
    # knowledge_file_path: path to the JSONL knowledge file used to seed the graph.
    #   Relative paths are resolved from the working directory where the server starts.
    #   The graph is rebuilt from this file on each server restart (no persistence needed).
    graph_enabled: bool = True
    knowledge_file_path: str = "data/knowledge/destinations.jsonl"

    # LLM-as-judge evaluation (Milestone 16)
    # judge_provider: "echo" (fixed score, no API call) or "bedrock".
    #   Always defaults to "echo" so the pipeline works without AWS credentials.
    # bedrock_judge_model_id: the judge model MUST differ from bedrock_llm_model_id
    #   to avoid common-mode bias.  Default is Amazon Nova Lite (distinct from Claude).
    #   Other independent options: mistral.mistral-large-2402-v1:0
    #                              meta.llama3-70b-instruct-v1:0
    judge_provider: str = "echo"
    bedrock_judge_model_id: str = "amazon.nova-lite-v1:0"


@lru_cache
def get_settings() -> Settings:
    """Return the cached singleton Settings instance.

    The cache ensures settings are parsed from the environment exactly once.
    In tests, call get_settings.cache_clear() after patching env vars.
    """
    return Settings()
