#!/usr/bin/env python3
"""Export Claude Code session(s) to docs/CHAT_HISTORY.md.

Usage
-----
    uv run python scripts/export_chat.py            # auto-detect session files
    uv run python scripts/export_chat.py session.jsonl ...   # explicit files

With no arguments the script locates all session JSONL files for the current
project directory under ~/.claude/projects/<sanitized-cwd>/ and writes their
conversation turns to docs/CHAT_HISTORY.md.

Wired as a Stop hook in .claude/settings.json so it runs automatically after
every Claude response.  The hook receives JSON on stdin but this script ignores
it and always does a full re-export (idempotent, cheap for typical session sizes).

What is exported
----------------
- User (human) messages, excluding slash-command invocations and injected
  system context blocks.
- Assistant messages, excluding thinking blocks and tool-call/result blocks
  (those are internal mechanics, not part of the readable conversation).

Output format
-------------
Markdown with one H2 section per session (sorted oldest→newest), and H3 turns
labelled "You" / "Claude".
"""

from __future__ import annotations

import json
import re
import sys
from datetime import datetime
from pathlib import Path

# ── Helpers ───────────────────────────────────────────────────────────────────

# Patterns that identify non-human content injected into user turns.
_INTERNAL_PATTERNS: list[re.Pattern[str]] = [
    re.compile(r"<command-message>"),
    re.compile(r"<command-name>"),
    re.compile(r"<system-reminder>"),
    re.compile(r"<function_calls>"),
    re.compile(r"<user-prompt-submit-hook>"),
]


def _sanitize_path(p: Path) -> str:
    """Convert an absolute path to the slug Claude uses for its project dirs."""
    return str(p).replace("/", "-")


def _find_session_files() -> list[Path]:
    """Return JSONL session files for the current working directory, oldest first."""
    slug = _sanitize_path(Path.cwd().resolve())
    project_dir = Path.home() / ".claude" / "projects" / slug
    if not project_dir.exists():
        return []
    files = sorted(project_dir.glob("*.jsonl"), key=lambda f: f.stat().st_mtime)
    return files


def _extract_text(content: str | list[dict]) -> str:  # type: ignore[type-arg]
    """Return the plain-text portion of a message content field.

    Skips thinking, tool_use, and tool_result blocks — only collects text blocks.
    """
    if isinstance(content, str):
        return content.strip()
    parts: list[str] = []
    for block in content:
        if isinstance(block, dict) and block.get("type") == "text":
            text = block.get("text", "").strip()
            if text:
                parts.append(text)
    return "\n\n".join(parts)


def _is_internal_user_message(text: str) -> bool:
    """Return True if this user turn is an internal command or system injection."""
    for pat in _INTERNAL_PATTERNS:
        if pat.search(text):
            return True
    # Blank after stripping tags
    if not text.strip():
        return True
    return False


# ── Parser ────────────────────────────────────────────────────────────────────


def parse_session(path: Path) -> list[dict[str, str]]:
    """Return a list of {role, text, ts} dicts from a session JSONL file."""
    turns: list[dict[str, str]] = []
    with path.open(encoding="utf-8") as fh:
        for raw in fh:
            raw = raw.strip()
            if not raw:
                continue
            try:
                obj = json.loads(raw)
            except json.JSONDecodeError:
                continue

            record_type = obj.get("type")
            if record_type not in ("user", "assistant"):
                continue

            msg = obj.get("message", {})
            role = msg.get("role")
            if role not in ("user", "assistant"):
                continue

            text = _extract_text(msg.get("content", ""))
            if not text:
                continue

            if role == "user" and _is_internal_user_message(text):
                continue

            turns.append(
                {
                    "role": role,
                    "text": text,
                    "ts": obj.get("timestamp", ""),
                }
            )
    return turns


# ── Renderer ──────────────────────────────────────────────────────────────────


def _format_ts(ts: str) -> str:
    if not ts:
        return ""
    try:
        dt = datetime.fromisoformat(ts.replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except ValueError:
        return ts


def render_markdown(sessions: list[tuple[str, list[dict[str, str]]]]) -> str:
    lines: list[str] = [
        "# Chat history — Travel AI Search",
        "",
        "> Auto-generated by `scripts/export_chat.py`.",
        "> Re-exported after every Claude response via the Stop hook.",
        "> Human turns are labelled **You**, assistant turns are labelled **Claude**.",
        "",
    ]
    for session_id, turns in sessions:
        if not turns:
            continue
        first_ts = turns[0].get("ts", "")
        label = _format_ts(first_ts) or session_id
        lines += [f"## Session — {label}", ""]
        for i, turn in enumerate(turns):
            heading = "### You" if turn["role"] == "user" else "### Claude"
            lines.append(heading)
            lines.append("")
            lines.append(turn["text"])
            lines.append("")
            if i < len(turns) - 1:
                lines += ["---", ""]
    return "\n".join(lines) + "\n"


# ── Main ──────────────────────────────────────────────────────────────────────


def main() -> None:
    # Allow explicit file paths; otherwise auto-detect.
    if len(sys.argv) > 1:
        files = [Path(p) for p in sys.argv[1:] if Path(p).exists()]
    else:
        files = _find_session_files()

    if not files:
        print("export_chat.py: no session files found.", file=sys.stderr)
        sys.exit(0)

    sessions: list[tuple[str, list[dict[str, str]]]] = []
    for f in files:
        turns = parse_session(f)
        sessions.append((f.stem, turns))

    out = Path("docs") / "CHAT_HISTORY.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_markdown(sessions), encoding="utf-8")

    total_turns = sum(len(t) for _, t in sessions)
    print(f"export_chat.py: {total_turns} turns from {len(sessions)} session(s) → {out}")


if __name__ == "__main__":
    main()
